# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Incubateur de Services Numériques
email: incubateur@sgmap.fr
description: Nous modernisons l'État et les administrations en produisant rapidement et durablement des outils numériques qui améliorent le service public.
baseurl: "/"
url: "http://sgmap.github.io"

collections:
  startups:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: startups	# targets a collection
    values:
      layout: startup
      logo: img/logo-generique-startup-carre.jpg
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

phases:
  incubation:
    investigation:
      name: investigation
      description: Un besoin est pressenti. Exploration des frictions rencontrées par les usagers, des métriques pertinentes, des contraintes techniques, sociales et politiques et identification des porteurs et du financement.
    construction:
      name: construction
      description: Le besoin a été avéré et le financement validé. Prototypage de solutions confrontées aux retours de toutes les parties prenantes et d'usagers testeurs.
    consolidation:
      name: consolidation
      description: Une solution a été validée par les usagers et considérée comme viable par les parties prenantes. Itérations face au public cible réel et passage progressif à l’échelle.
    passation:
      name: passation
      description: La solution est viable et un repreneur institutionnel a été identifié. Ce repreneur est formé à la maintenance et l'amélioration continue du service.
  endgame:
    success:
      name: succès
      description: Le service est opéré par son repreneur institutionnel.
    retirement:
      name: retraite
      description: Le service a été rendu obsolète par des évolutions techniques, règlementaires ou d’usage, et il a été fermé en lien avec les partenaires, les usagers et son éventuel successeur.
    death:
      name: abandon
      description: Le service a été abandonné en cours de construction. Un postmortem explique l’abandon pour le capitaliser.

# Build settings
markdown: kramdown
