# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Incubateur de Services Numériques de l'État
email: incubateur@sgmap.fr
description: Nous créons des services publics numériques
baseurl: "/"
url: "http://sgmap.github.io"

collections:
  startups:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: startups	# targets a collection
    values:
      layout: startup
      logo: /img/logo-generique-startup-carre.jpg
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

phases:
  incubation:
    investigation:
      name: investigation
      description: Une friction avec l’usager est identifiée. Les volumes et contraintes sont déterminées. Porteur(s) et financement sont validés. Une équipe autonome de 2 à 4 personnes est constituée.
      featured: psi
    construction:
      name: construction
      description: L’équipe comprend le besoin et construit un produit de manière itérative et incrémentale pour y répondre. Des volontaires l'expérimentent en conditions réelles.
      featured: ban
    consolidation:
      name: consolidation
      description: Le produit est utilisé par les volontaires pilotes. L'équipe améliore le service et élargit son public cible selon les retours.
      featured: labonneboite
    passation:
      name: passation
      description: Le service est viable et un repreneur institutionnel a été identifié. Celui-ci prend progressivement en charge la maintenance et l'amélioration continue du service.
  endgame:
    success:
      name:
        singular: reprise
        plural: reprises
      description: Le service est opéré de manière pérenne par son repreneur institutionnel.
    retirement:
      name:
        singular: fermée
        plural: fermées
      description: Le service a été rendu obsolète par des évolutions techniques, règlementaires ou d’usage. Il a été fermé en lien avec les partenaires, les usagers et son éventuel successeur.
    death:
      name:
        singular: abandonnée
        plural: abandonnées
      description: Le service a été abandonné en cours de construction. L'abandon est expliqué pour capitaliser sur l'expérience accumulée.

# Build settings
markdown: kramdown
