# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Incubateur de Services Numériques
email: incubateur@data.gouv.fr
description: Nous modernisons l'État et les administrations en produisant rapidement et durablement des outils numériques qui améliorent le service public.
# baseurl: ""
# url: "https://beta.gouv.fr"

# Build settings
markdown: kramdown
