# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: Incubateur de Services Numériques
email: incubateur@data.gouv.fr
description: Nous modernisons l'État et les administrations en produisant rapidement et durablement des outils numériques qui améliorent le service public.
baseurl: "/lolilolol/"
url: "http://mattisg.github.io"

collections:
  startups:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: startups	# targets a collection
    values:
      layout: startup
      logo: img/logo-generique-startup-carre.jpg
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

phases:
  discovery:
    name: découverte
    description: 3 à 6 semaines pendant lesquelles les besoins utilisateur sont assimilés, les métriques pertinentes définies, et les contraintes techniques, sociales et politiques explorées.
  alpha:
    name: alpha
    description: 4 à 8 semaines pendant lesquelles des solutions sont prototypées pour répondre aux besoins déterminés en Découverte, et confrontées aux retours de toutes les parties prenantes et de testeurs.
  beta:
    name: bêta
    description: Plusieurs mois pendant lesquels la solution validée en Alpha est développée de manière itérative, face à son public cible réel, et passe progressivement à l’échelle.
  live:
    name: production
    description: Durée indéterminée pendant laquelle le service continue à s’améliorer, en répondant aux besoins émergents, aux évolutions techniques, aux nouvelles contraintes…
  retirement:
    name: retraite
    description: Lorsqu’un service est rendu obsolète par des évolutions techniques, règlementaires ou d’usage, il est fermé en lien avec les partenaires, les usagers et en prenant soin des données qui y ont transité.

# Build settings
markdown: kramdown
